In [4]:
#Lab2

In [1]:
import warnings
warnings.simplefilter('ignore')

import pandas as pd

df = pd.read_csv('s3://ia-340-2025-fall-1551/Chesapeake_Bay_Pollution_Loads_-_Nitrogen.csv') # load data from s3 bucket
df.head() #show the first 5 rows

,Land-River Segment,FIPS,County,Tributary Basin,Major Basin,Source Sector,"Total N, 1985 (lb.)","Total N, 2007 (lb.)","Total N, 2009 (lb.)","Total N, 2010 (lb.)","Total N, 2011 (lb.)","Total N, 2012 (lb.)","Total N, 2013 (lb.)","Total N, 2014 (lb.)","Total N, 2015 (lb.)","Total N, 2016 (lb)","Total N Target, 2017 (lb.)",Total N Target 2025 (lb.)
0,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Forest,51155.919439,44291.188482,44013.497319,44071.130371,44127.954834,44065.744141,43439.700192,42644.769651,42279.000084,43150.365479,44567.218760,44936.366387
1,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Non-Tidal Atm,23.744801,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600469,11.600469
2,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Septic,593.984192,539.573425,534.814819,532.096191,530.284119,527.565125,687.846619,553.043579,547.539978,542.895386,466.803913,421.463309
3,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Stormwater,4163.487261,2510.113876,2473.745250,2463.564675,2455.817180,2456.445068,5187.855037,2569.293440,2718.073060,2686.010203,2278.617397,2148.532161
4,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Wastewater,153.179901,54.931515,298.770703,111.263985,113.858285,101.050881,93.216107,170.578984,0.902378,68.777241,160.712233,68.673253

In [2]:
df.shape  #identify the amount of rows and columns

(4086, 18)

In [3]:
df.info()   #Showing the types of data and amount of null values, mainly numeric with some collumns talking about location and water type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4086 entries, 0 to 4085
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Land-River Segment          4086 non-null   object
 1   FIPS                        4086 non-null   int64
 2   County                      4086 non-null   object
 3   Tributary Basin             4086 non-null   object
 4   Major Basin                 4086 non-null   object
 5   Source Sector               4086 non-null   object
 6   Total N, 1985 (lb.)         4086 non-null   float64
 7   Total N, 2007 (lb.)         4086 non-null   float64
 8   Total N, 2009 (lb.)         4086 non-null   float64
 9   Total N, 2010 (lb.)         4080 non-null   float64
 10  Total N, 2011 (lb.)         4056 non-null   float64
 11  Total N, 2012 (lb.)         4056 non-null   float64
 12  Total N, 2013 (lb.)         4056 non-null   float64
 13  Total N, 2014 (lb.)         4056 non-null   float64
 14  Total N, 2015 (lb.)         4056 non-null   float64
 15  Total N, 2016 (lb)          4056 non-null   float64
 16  Total N Target, 2017 (lb.)  4086 non-null   float64
 17  Total N Target 2025 (lb.)   3755 non-null   float64
dtypes: float64(12), int64(1), object(5)
memory usage: 574.7+ KB

In [5]:
df.describe()  #Statisitcal summary showing pollution levels

,FIPS,"Total N, 1985 (lb.)","Total N, 2007 (lb.)","Total N, 2009 (lb.)","Total N, 2010 (lb.)","Total N, 2011 (lb.)","Total N, 2012 (lb.)","Total N, 2013 (lb.)","Total N, 2014 (lb.)","Total N, 2015 (lb.)","Total N, 2016 (lb)","Total N Target, 2017 (lb.)",Total N Target 2025 (lb.)
count,4086.000000,4.086000e+03,4.086000e+03,4.086000e+03,4.080000e+03,4.056000e+03,4.056000e+03,4.056000e+03,4.056000e+03,4.056000e+03,4.056000e+03,4.086000e+03,3.755000e+03
mean,24033.531571,1.990067e+04,1.353891e+04,1.271365e+04,1.293037e+04,1.236455e+04,1.231798e+04,1.172807e+04,1.228175e+04,1.185644e+04,1.183132e+04,1.113098e+04,1.096405e+04
std,70.382792,1.746379e+05,6.517908e+04,6.041588e+04,6.247598e+04,5.811273e+04,5.652281e+04,5.613043e+04,5.973209e+04,5.714131e+04,5.870386e+04,5.097557e+04,4.899446e+04
min,24001.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,24013.000000,0.000000e+00,1.243952e+01,1.295082e+01,1.274332e+01,1.433810e+01,1.430155e+01,7.099127e+00,6.563637e+00,6.087110e+00,6.411704e+00,1.277007e+01,4.550224e+01
50%,24025.000000,8.311226e+02,9.340047e+02,9.319247e+02,9.432373e+02,9.638791e+02,9.657926e+02,8.017383e+02,7.702859e+02,7.462348e+02,7.738196e+02,8.416243e+02,1.010698e+03
75%,24037.000000,7.261174e+03,6.714139e+03,6.494633e+03,6.551888e+03,6.495979e+03,6.496096e+03,6.150168e+03,6.075436e+03,6.130585e+03,6.091330e+03,5.988873e+03,6.144619e+03
max,24510.000000,8.044738e+06,1.922870e+06,1.696879e+06,1.657799e+06,1.503248e+06,1.504427e+06,1.476687e+06,1.548325e+06,1.616374e+06,1.655468e+06,1.220035e+06,1.261108e+06

In [6]:
df = df.rename(columns={"Tributary Basin": " T Basin", "Major Basin": " M Basin" }) 
df.head()
# Renaming columns to shorten nthe ame so it is more user-friendly

,Land-River Segment,FIPS,County,T Basin,M Basin,Source Sector,"Total N, 1985 (lb.)","Total N, 2007 (lb.)","Total N, 2009 (lb.)","Total N, 2010 (lb.)","Total N, 2011 (lb.)","Total N, 2012 (lb.)","Total N, 2013 (lb.)","Total N, 2014 (lb.)","Total N, 2015 (lb.)","Total N, 2016 (lb)","Total N Target, 2017 (lb.)",Total N Target 2025 (lb.)
0,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Forest,51155.919439,44291.188482,44013.497319,44071.130371,44127.954834,44065.744141,43439.700192,42644.769651,42279.000084,43150.365479,44567.218760,44936.366387
1,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Non-Tidal Atm,23.744801,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600470,11.600469,11.600469
2,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Septic,593.984192,539.573425,534.814819,532.096191,530.284119,527.565125,687.846619,553.043579,547.539978,542.895386,466.803913,421.463309
3,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Stormwater,4163.487261,2510.113876,2473.745250,2463.564675,2455.817180,2456.445068,5187.855037,2569.293440,2718.073060,2686.010203,2278.617397,2148.532161
4,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Wastewater,153.179901,54.931515,298.770703,111.263985,113.858285,101.050881,93.216107,170.578984,0.902378,68.777241,160.712233,68.673253

In [7]:
df.isnull().sum()  #locating rows with null values

Land-River Segment              0
FIPS                            0
County                          0
 T Basin                        0
 M Basin                        0
Source Sector                   0
Total N, 1985 (lb.)             0
Total N, 2007 (lb.)             0
Total N, 2009 (lb.)             0
Total N, 2010 (lb.)             6
Total N, 2011 (lb.)            30
Total N, 2012 (lb.)            30
Total N, 2013 (lb.)            30
Total N, 2014 (lb.)            30
Total N, 2015 (lb.)            30
Total N, 2016 (lb)             30
Total N Target, 2017 (lb.)      0
Total N Target 2025 (lb.)     331
dtype: int64

In [8]:
df = df.dropna() #drop null values becuase they will create gaps in data

In [ ]:
# I renamed the Basin Names to make them shorter, I found 517 null values within the data, I dropped those values to elimnate gaps.

In [10]:
df.sort_values(by='County') #sort data by a column I chose by County

,Land-River Segment,FIPS,County,T Basin,M Basin,Source Sector,"Total N, 1985 (lb.)","Total N, 2007 (lb.)","Total N, 2009 (lb.)","Total N, 2010 (lb.)","Total N, 2011 (lb.)","Total N, 2012 (lb.)","Total N, 2013 (lb.)","Total N, 2014 (lb.)","Total N, 2015 (lb.)","Total N, 2016 (lb)","Total N Target, 2017 (lb.)",Total N Target 2025 (lb.)
0,A24001PU0_3871_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Forest,51155.919439,44291.188482,44013.497319,44071.130371,44127.954834,44065.744141,43439.700192,42644.769651,42279.000084,43150.365479,44567.218760,44936.366387
2978,B24001PU4_3890_3990,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Non-Tidal Atm,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2979,B24001PU4_3890_3990,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Septic,33.177662,24.883240,24.576700,24.428631,24.206570,23.984591,23.690630,19.977970,20.018511,19.903820,21.440378,19.349497
2980,B24001PU4_3890_3990,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Stormwater,53.462856,39.739029,39.149228,38.908802,38.869784,38.786151,8.598408,8.561445,8.425805,8.455146,35.999499,33.899680
2981,B24001PU4_3890_3990,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Wastewater,266.932587,266.932587,266.932587,266.932587,444.780395,444.780395,444.780395,444.780395,444.780396,444.780396,283.361369,294.313890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872,A24047EL3_5870_0000,24047,WORCESTER,Lower Eastern Shore,Eastern Shore of Chesapeake Bay,Agriculture,274944.797000,150557.081140,113499.430600,159446.578850,147878.472340,130210.292840,120305.536030,141687.995410,138004.513462,138314.089643,121046.363518,126077.652130
2871,A24047EL2_5270_0001,24047,WORCESTER,Lower Eastern Shore,Eastern Shore of Chesapeake Bay,Wastewater,0.000000,32.411201,32.411201,32.411201,32.411201,32.411201,32.389019,32.389019,32.389019,32.389019,32.381929,32.362414
2870,A24047EL2_5270_0001,24047,WORCESTER,Lower Eastern Shore,Eastern Shore of Chesapeake Bay,Stormwater,7856.618690,9172.777435,8771.918456,9604.394943,9380.991990,9827.172043,8182.793014,8527.876999,8555.068573,8521.947258,8506.712886,8329.909172
2881,A24047EL3_5970_0000,24047,WORCESTER,Lower Eastern Shore,Eastern Shore of Chesapeake Bay,Septic,1624.187988,1996.387939,2106.737061,2129.322998,2159.738037,2181.523926,3291.742920,1829.234009,1823.297974,1803.685059,1593.127406,1250.720969
2866,A24047EL2_5270_0001,24047,WORCESTER,Lower Eastern Shore,Eastern Shore of Chesapeake Bay,Agriculture,302548.104190,165672.258090,124896.995110,175452.340790,161651.487900,143276.148990,132382.302750,155910.633140,151860.200138,152207.571332,157413.056236,179090.430320

In [11]:
df[5:10]  # slicing rows 5 through 10

,Land-River Segment,FIPS,County,T Basin,M Basin,Source Sector,"Total N, 1985 (lb.)","Total N, 2007 (lb.)","Total N, 2009 (lb.)","Total N, 2010 (lb.)","Total N, 2011 (lb.)","Total N, 2012 (lb.)","Total N, 2013 (lb.)","Total N, 2014 (lb.)","Total N, 2015 (lb.)","Total N, 2016 (lb)","Total N Target, 2017 (lb.)",Total N Target 2025 (lb.)
5,A24001PU1_3100_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Agriculture,15441.999299,6334.096958,5363.781002,5447.929184,5298.208617,4807.539082,4257.630570,7078.612716,6868.731842,6590.542831,5426.166399,5467.756663
6,A24001PU1_3100_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Forest,12118.457643,11013.503664,10978.346189,11011.178284,11052.815187,11051.169738,10846.244142,10585.300400,10523.757990,10762.613464,11117.065084,11209.544348
7,A24001PU1_3100_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Non-Tidal Atm,29.312059,14.320330,14.320330,14.320330,14.320330,14.320330,14.320330,14.320330,14.320330,14.320330,14.320331,14.320331
8,A24001PU1_3100_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Septic,0.000000,358.963196,346.295990,340.453308,337.114594,333.780609,403.322693,328.679504,322.664886,319.099792,300.319283,269.668145
9,A24001PU1_3100_3690,24001,ALLEGANY,Upper Potomac,Potomac River Basin,Stormwater,2093.073410,1496.256920,1479.859032,1454.163757,1450.836548,1453.361450,2195.390412,1547.939217,1586.918999,1577.706947,1352.332433,1267.314701

In [ ]:
# for this section I chose to sort by column and used county to ensure easy access to county specific data, then I sliced to look at rows 5 to 10.